version: "3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DB_URL: mongodb+srv://supun:supun123@cluster0.m8tkmsl.mongodb.net/?retryWrites=true&w=majority
      SECRET: AIULHG4763Q9T89TNGUE98GE
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
#run command
# docker compose up
